services:
  - type: web
    name: CleanScrape
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
